### YamlMime:FAQ
metadata:
  title: Product and licensing FAQ
  titleSuffix: Configuration Manager
  description: Find answers for common product and license questions for Configuration Manager.
  ms.date: 05/12/2022
  ms.prod: configuration-manager
  ms.technology: configmgr-core
  ms.topic: faq
  author: aczechowski
  ms.author: aaroncz
  manager: dougeby
  ms.collection: highpri

title: Frequently asked questions for Configuration Manager branches and licensing
summary: |
  *Applies to: Configuration Manager (current branch) & System Center Configuration Manager (long-term servicing branch)*
  
  This FAQ addresses common licensing questions about Configuration Manager current branch and the long-term servicing branch (LTSB) versions, available through Microsoft Volume Licensing programs. This article is for informational purposes. It doesn't supersede or replace any documentation covering Configuration Manager licensing. For more information, see the [Product Terms](https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=53). The Product Terms describe the use terms for all Microsoft products in Volume Licensing.
  

sections:
  - name: Ignore
    questions:
      - question: |
          What's current branch?
        answer: |
          The current branch is the production-ready build of Configuration Manager that provides an active servicing model. This servicing model is like the experience with Windows. This approach supports customers who are moving at a cloud cadence and wish to innovate more quickly. With the current branch servicing model, you continue to receive new features and functionality. For this reason, only customers with active Software Assurance on Configuration Manager licenses, or with equivalent subscription rights, may install and use the current branch of Configuration Manager.

      - question: |
          What's the long-term servicing branch (LTSB)?  
        answer: |
          The LTSB is a production-ready build of Configuration Manager. It's intended for customers who allow Software Assurance or equivalent subscription rights to expire. When compared to the current branch, the LTSB has [reduced functionality](introduction-to-the-ltsb.md#features-that-arent-available). Customers who allow Software Assurance or equivalent subscription rights to expire must uninstall the current branch of Configuration Manager. Customers who have perpetual license rights to Configuration Manager may then install and use the LTSB build of the Configuration Manager version that's current at the time of expiration.
          
      - question: |
          What do the acronyms 'SA' and 'L&SA' mean in regard to Configuration Manager?
        answer: |
          Both **Software Assurance** (SA) and **License and Software Assurance** (L&SA) are license options that grant rights to use Configuration Manager. SA is an option for a customer that's renewing SA coverage from a prior agreement. L&SA is an option for a customer buying a new license and SA coverage.
          
          - **Software Assurance (SA)**: Customers must have active SA on Configuration Manager licenses, or equivalent subscription rights, in order to install and use the current branch option of Configuration Manager.
          
            While SA is optional for some Microsoft products, the only way to get rights to use Configuration Manager current branch is with SA *or equivalent subscription rights*. For more information, see the [Software Assurance FAQ](https://www.microsoft.com/licensing/licensing-programs/FAQ-Software-Assurance.aspx).
          
          - **Microsoft License and Software Assurance (L&SA)**: Customers buying new licenses for Configuration Manager must acquire L&SA (the license and SA coverage).
          
            - The SA grants rights to use the current branch.
          
            - If your SA expires, and you still have a license for Configuration Manager, you can no longer use the current branch. For more information, see the FAQ [If my SA expires and I had L&SA, what do I get?](#if-my-sa-expires--and-i-had-l-sa--what-do-i-get-)
          
          For more information about license offerings, see [Ways to buy](https://www.microsoft.com/Licensing/licensing-programs/licensing-programs) and [Licensing Product Terms](https://www.microsoftvolumelicensing.com/ProductResults.aspx?doc=Product%20Terms,OST&fid=64).  
          
      - question: |
          What are 'equivalent subscriptions'?
        answer: |
          Equivalent subscriptions refer to programs like [Enterprise Mobility + Security](https://www.microsoftvolumelicensing.com/ProductResults.aspx?doc=Product%20Terms,OST&fid=51) (EMS) or [Microsoft 365 Enterprise](https://www.microsoft.com/microsoft-365/enterprise). There can be others, but these programs are the most common. The Microsoft Volume Licensing Product Terms refers to these programs as Management License Equivalent Licenses.
          
          Configuration Manager is included in the following plans:
          
          - Intune user subscription license (USL)
          - EMS E3
          - EMS E5
          - Microsoft 365 E3
          - Microsoft 365 E5
          - Microsoft 365 F3 (formerly Microsoft 365 F1)
          
          <!-- Sources:
          https://www.microsoft.com/microsoft-365/compare-all-microsoft-365-plans
          https://www.microsoft.com/microsoft-365/enterprise-mobility-security/compare-plans-and-pricing
          -->
          
          > [!IMPORTANT]
          > Configuration Manager isn't included in the [Microsoft 365 Business Premium](https://www.microsoft.com/microsoft-365/business) plan.
          
      - question: |
          What changes with licensing for co-management in Microsoft Endpoint Manager?
        answer: |
          <!-- 7202432 -->
          
          The co-management license lets Configuration Manager customers with Software Assurance get Intune PC management rights without having to purchase and assign individual Intune licenses to users. This license makes it easier for you to manage Windows devices with Microsoft Endpoint Manager.
          
          - Devices already managed by Configuration Manager that you enroll to Intune for co-management have almost the same rights as an Intune standalone-managed PC. If you reset Windows on this device, you can't provision it with Windows Autopilot. Autopilot requires a full Intune license.
          
          - If you enroll a Windows device to Intune by other means, it still requires a full Intune license. For example, you use Autopilot to provision a device, or a user manually does self-service enrollment.
          
          - For existing Configuration Manager-managed devices to enroll into Intune for co-management at scale without user interaction, co-management uses an Azure Active Directory (Azure AD) feature called Windows auto-enrollment. Auto-enrollment with co-management requires licenses for both Azure AD Premium (AADP1) and Intune. Starting on December 1, 2019, you no longer need to assign individual Intune licenses for this scenario. Microsoft Endpoint Manager now includes the Intune licenses for co-management. The separate AADP1 licensing requirement remains the same for this scenario to work. You still need to assign Intune licenses for other enrollment scenarios.
          
          - If you want to use Intune for managing iOS, Android, or macOS devices, then you need the appropriate Intune subscription through a standalone Intune license, Enterprise Mobility + Security (EMS), or Microsoft 365.
          
          - If you don't have any Intune-related subscription plan, to support co-management you need to purchase at least one Intune license. This license is for an administrator to activate the subscription plan and get access to the Microsoft Endpoint Manager admin center.
          
          - If you use the Microsoft 365 built-in [Basic Mobility and Security](https://support.microsoft.com/office/capabilities-of-built-in-mobile-device-management-for-microsoft-365-a1da44e5-7475-4992-be91-9ccec25905b0), you can't use the new co-management license for a user that also has devices managed by Basic Mobility and Security. To use the co-management license for the user's Configuration Manager-managed device, do one of the following actions:
          
            - Assign a full Intune license to the user, and manage their devices through Intune.
            - Unenroll the devices from Basic Mobility and Security.
          
          - The licensing that you previously had for System Center Configuration Manager still applies to Microsoft Endpoint Configuration Manager. If installing a new site, use existing product keys.
          
          |Feature | Co-management license | Full Intune license |
          |---------|---------|---------|
          |Windows enrollment|Yes (only for existing ConfigMgr-managed devices)|Yes|
          |iOS, Android, macOS enrollment|No|Yes|
          |Autopilot|No|Yes|
          |Mobile Application Management (MAM)|No|Yes|
          |Conditional access<br>(additional AADP1 required)|Yes|Yes|
          |Device profiles|Yes|Yes|
          |Software update management|Yes|Yes|
          |Inventory|Yes|Yes|
          |App management|Yes|Yes|
          |Remote Full/Selective wipe|Yes|Yes|
          |Remote assistance<br>(TeamViewer license required)|Yes|Yes|
          |Desktop analytics<br>(Windows subscription licenses required|Yes|N/A|
          |Tenant attach|Yes|N/A|
          |Endpoint analytics|Yes|Yes|
          
          For more information, see the following articles:
          
          - [Co-management prerequisites](../../comanage/overview.md#prerequisites)
          - [Windows Autopilot requirements](/windows/deployment/windows-autopilot/windows-autopilot-requirements)
          - [Desktop analytics prerequisites](../../desktop-analytics/overview.md#prerequisites)
          - [Tenant attach prerequisites](../../tenant-attach/prerequisites.md)
          - [Endpoint analytics licensing prerequisites](../../../analytics/overview.md#licensing-prerequisites)
          - [Use conditional access with Intune](../../../intune/protect/conditional-access.md#ways-to-use-conditional-access-with-intune)
          - [TeamViewer prerequisites](../../../intune/remote-actions/teamviewer-support.md#prerequisites)
          
      - question: |
          I have Enterprise Mobility + Security and it expired, what must I do now?  
        answer: |
          EMS grants rights to use Configuration Manager current branch and long-term service branch. When these rights expire, you no longer have rights to use either branch and must uninstall.  

      - question: |
          If my SA expires, and I had L&SA, what do I get?
        answer: |
          If your SA expired after October 1, 2016, depending on what program you acquired L&SA under, you could retain a perpetual license to use the LTSB. If you currently use the current branch, you must uninstall it, and then install the LTSB. There's no support to migrate or convert to the LTSB from the current branch.
          
          If your SA expired before October 1, 2016, and you retained a perpetual license to Configuration Manager, then your only option for ongoing use is to install and use System Center 2012 R2 Configuration Manager and its available service packs. You're required to uninstall the current branch when your SA expires, and reinstall that earlier version of the product. There's no support to migrate to or downgrade from Configuration Manager current branch to prior versions of Configuration Manager.
          
          If you use System Center Endpoint Protection, and your SA expires, you must uninstall it. System Center Endpoint Protection offers no *L (License)* rights, and no perpetual rights.<!--506238-->
          
      - question: |
          Do I "own" the current branch?
        answer: |
          No. You're licensed to use the current branch while you have active SA. For example, via *L&SA*, when *SA* expires, you then have only *L (License)* rights, which don't include rights to use the current branch. If your L provides perpetual rights, you can use the Configuration Manager LTSB in place of the current branch. If your SA expired prior to October 1, 2016, you can also use System Center 2012 R2 Configuration Manager.

      - question: |
          Can I purchase Configuration Manager standalone without SA?
        answer: |
          No. The only way to get rights to use Configuration Manager is to acquire a license with SA or through an equivalent subscription. There are developer programs like MSDN where Configuration Manager is offered for development and test purposes, but not production usage.

      - question: |
          Does a non-production environment for testing or development require an explicit license?
        answer: |
          <!-- SCCMDocs#1848 -->
          
          - If you use the same current branch software as your production environment, you need an explicit license. Check with your account team to determine if your specific license agreement covers multiple instances in multiple environments.
          
          - Some developer programs like MSDN offer products like Configuration Manager for development and test, but not production use.
          
<<<<<<< HEAD
          - For a temporary environment, you can use the [evaluation version](https://www.microsoft.com/evalcenter/download-microsoft-endpoint-configuration-manager) for 180 days.
=======
          - For a temporary environment, you can use the evaluation version for 180 days.
>>>>>>> 8b4ccbb418343ae2ae27bbaf01cf7fda148b00c2
          
              > [!NOTE]
              > The Evaluation Center is currently unavailable. As a workaround you can download the current branch evaluation from [aka.ms/MECM2203CB-Eval](https://aka.ms/MECM2203CB-Eval).<!-- 14437681 -->

          - For a lab environment, you can use the [technical preview branch](../get-started/technical-preview.md). Technical preview has the same functionality as current branch, but has some limitations in terms of scale and supported platforms.
          
      - question: |
          Do I have rights to install any update in the Configuration Manager console?
        answer: |
          If you have active *SA*, you do have rights.
          
          If you don't have active SA, uninstall the current branch, and then install the LTSB of Configuration Manager. The LTSB doesn't receive updates for incremental versions of Configuration Manager, but does receive security updates based on the Support Lifecycle.
          
      - question: |
          I have purchased EMS or Microsoft 365 through a Cloud Solution Provider (CSP), do I have rights to use Configuration Manager?
        answer: |
<<<<<<< HEAD
          Yes, you have rights to use Configuration Manager to manage clients covered by the EMS license. First download and install the [evaluation software](https://www.microsoft.com/evalcenter/download-microsoft-endpoint-configuration-manager). Then contact your CSP partner to obtain the license key from the Microsoft Partner Center support team, specifically CSP.<!--SCCMDocs#472,OSGS 33035978--> When your CSP partner talks with Microsoft Support, they should ask them to reference the internal article ID 4033838.<!--SCCMDocs#493-->
=======
          Yes, you have rights to use Configuration Manager to manage clients covered by the EMS license. First download and install the evaluation software. Then contact your CSP partner to obtain the license key from the Microsoft Partner Center support team, specifically CSP.<!--SCCMDocs#472,OSGS 33035978--> When your CSP partner talks with Microsoft Support, they should ask them to reference the internal article ID 4033838.<!--SCCMDocs#493-->
>>>>>>> 8b4ccbb418343ae2ae27bbaf01cf7fda148b00c2
          
          > [!NOTE]
          > The Evaluation Center is currently unavailable. As a workaround you can download the current branch evaluation from [aka.ms/MECM2203CB-Eval](https://aka.ms/MECM2203CB-Eval).<!-- 14437681 -->

      - question: |
          Is my subscription end-date the same as an SA expiration date?
        answer: |
          If *SA* or your subscription is active, you have use rights for Configuration Manager current branch. An active subscription is equivalent of having active *SA*, but no perpetual *"L" (license)*. Once your subscription is over, uninstall the current branch. At this time, you don't have rights to use the LTSB.  

      - question: |
          What are the use rights associated with the SQL Server technology provided with Configuration Manager?
        answer: |
          Configuration Manager includes SQL Server technology. Microsoft's licensing terms for this product allows your use of SQL Server technology only to support Configuration Manager components. SQL Server client access licenses are not required for that use.
          
          Approved use rights for the SQL Server capabilities with Configuration Manager include:
          
          - Site database role
          - Windows Server Update Services (WSUS) for software update point role
          - SQL Server Reporting Services (SSRS) for reporting point role
          - Data warehouse service point role
          - Database replicas for management point roles
          
          The SQL Server license that's included with Configuration Manager supports each instance of SQL Server that you install to host a database for Configuration Manager. However, only databases for Configuration Manager in the preceding list can run on that SQL Server when you use this license. If a database for any additional Microsoft or third-party product shares the SQL Server, you must have a separate license for that SQL Server instance.
           <!-- sms500967 -->
          
      - question: |
          Does on-premises mobile device management (MDM) require an Intune subscription?
        answer: |
          No. An Intune connection isn't required for new on-premises MDM deployments.<!--3607730, fka 1359124--> Your organization still requires Intune licenses to use this feature. For more information, see the [Intune support blog post](https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Move-from-Hybrid-Mobile-Device-Management-to-Intune-on-Azure/ba-p/280150).
