# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

permissions:
  issues: write
  pull-requests: write
  
on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 120
        days-before-pr-close: 130
        stale-pr-label: 'inactive'
        close-pr-label: 'auto-close'
        exempt-pr-label: 'keep-open'
        stale-pr-message: > 
           This pull request has been inactive for 120 days. If you are finished with your changes, resolve any merge conflicts and/or validation warnings, and add a **#sign-off** comment. For instructions, see the [MSec Docs Self-Serve Playbook](https://aka.ms/MSecDocsSelfServePlaybook).
           <br/>
           <br/>If this PR is inactive for 10 more days it will be closed automatically. Thank you!
           <br/>
           <br/>If you have a question, post on the MSEC Documentation Excellence Program [Ask an Admin](https://teams.microsoft.com/l/channel/19%3A0cdb9988d02e4f78bef37d571686ec5b%40thread.tacv2/Ask%20an%20Admin?groupId=8b6faa31-5d02-4e94-90eb-f1944d5c40fd&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) Teams channel.      
        close-pr-message: >
           <br/>This pull request has been inactive for 130 days. At this time we're closing the PR.
           <br/>
           <br/>If you decide to continue working on your changes, you can reopen the PR and continue working. Thank you!
           <br/>
           <br/>If you have a question, post on the MSEC Documentation Excellence Program [Ask an Admin](https://teams.microsoft.com/l/channel/19%3A0cdb9988d02e4f78bef37d571686ec5b%40thread.tacv2/Ask%20an%20Admin?groupId=8b6faa31-5d02-4e94-90eb-f1944d5c40fd&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) Teams channel.